#include "stack.h"
#include <stdlib.h>
#include <string.h>
#include <assert.h>


stack *stack__create(int max_elems)
{
  // fill this in
  return NULL;  // dummy return value
}

stack * stack__create_copy(stack * s)
{
  // fill this in
  return NULL;  // dummy return value
}

void stack__destroy(stack * s)
{
  // fill this in
}

bool stack__is_empty(stack *s)
{
  // fill this in
  return true;  // dummy return value
}

bool stack__is_full(stack *s)
{
  // fill this in
  return false; // dummy return value
}

double stack__pop(stack *s)
{
  // fill this in
  return 0;     // dummy return value
}

void stack__push(stack *s, double data)
{
  // fill this in
}

