/* This module demonstrates the construction from a directed multigraph of
   the type defined in graphtrans.h of an NFA transition table with start
   and final states.
*/

/* This module is to be designed and implemented by the student.  This is
   one example of an approach you may want to use.  A transition table,
   represented by a 2 dimensional array containing pointers to arrays of
   successor states indexed by values of states and inputs is an excellent
   way of representing an NFA, and is far more efficient than keeping your
   NFA in graph form.  (You may want to save space by implementing this as
   a sparse matrix, but that is not necessary).
*/

#ifndef NFA_H_
#define NFA_H_

#include "parser.h"
#include "graphtrans.h"

#endif
