# NOTE: this is a GNU Makefile.  You must use "gmake" rather than "make".

SIMOS = 1
include ../Makefile.ALL

#-----------------------------------------------------------------
# DO NOT DELETE THIS LINE -- make depend uses it
# DEPENDENCIES MUST END AT END OF FILE
bitmap.o: ../../lib/bitmap.cc ../../lib/copyright.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../lib/bitmap.h
debug.o: ../../lib/debug.cc ../../lib/copyright.h ../../lib/utility.h \
 ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h
hash.o: ../../lib/hash.cc ../../lib/copyright.h
libtest.o: ../../lib/libtest.cc ../../lib/copyright.h \
 ../../lib/libtest.h ../../lib/bitmap.h ../../lib/utility.h \
 ../../lib/list.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../lib/list.cc \
 ../../lib/hash.h ../../lib/hash.cc
list.o: ../../lib/list.cc ../../lib/copyright.h
sysdep.o: ../../lib/sysdep.cc ../../lib/copyright.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 /usr/class/cs240a/w97/mips-sgi/include/unistd.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/unistd.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/time.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/file.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/fcntl.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/socket.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/un.h
interrupt.o: ../../simos/interrupt.cc ../../lib/copyright.h \
 ../../simos/interrupt.h ../../lib/list.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../lib/list.cc \
 ../../simos/callback.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../simos/stats.h ../../threads/alarm.h \
 ../../simos/timer.h ../../filesys/synchdisk.h ../../simos/disk.h
stats.o: ../../simos/stats.cc ../../lib/copyright.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../simos/stats.h
timer.o: ../../simos/timer.cc ../../lib/copyright.h \
 ../../simos/timer.h ../../lib/utility.h ../../simos/callback.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/stats.h ../../threads/alarm.h \
 ../../filesys/synchdisk.h ../../simos/disk.h
alarm.o: ../../threads/alarm.cc ../../lib/copyright.h \
 ../../threads/alarm.h ../../lib/utility.h ../../simos/callback.h \
 ../../simos/timer.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/sysdep.h /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/stats.h ../../filesys/synchdisk.h \
 ../../simos/disk.h
kernel.o: ../../threads/kernel.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h ../../threads/synch.h ../../threads/synchlist.h \
 ../../threads/synchlist.cc ../../lib/libtest.h \
 ../../simos/elevatortest.h
main.o: ../../threads/main.cc ../../lib/copyright.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/utility.h \
 ../../lib/sysdep.h /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h
scheduler.o: ../../threads/scheduler.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../simos/interrupt.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h
synch.o: ../../threads/synch.cc ../../lib/copyright.h \
 ../../threads/synch.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h
synchlist.o: ../../threads/synchlist.cc ../../lib/copyright.h \
 ../../threads/synchlist.h ../../lib/list.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../lib/list.cc \
 ../../threads/synch.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../simos/interrupt.h \
 ../../simos/callback.h ../../simos/stats.h ../../threads/alarm.h \
 ../../simos/timer.h ../../filesys/synchdisk.h ../../simos/disk.h \
 ../../threads/synchlist.cc
thread.o: ../../threads/thread.cc ../../lib/copyright.h \
 ../../threads/thread.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../simos/machine.h \
 ../../simos/translate.h ../../lib/debug.h ../../simos/registers.h \
 ../../simos/simos.h ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/switch.h ../../threads/synch.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h
elevatortest.o: ../../simos/elevatortest.cc ../../lib/copyright.h \
 ../../simos/elevatortest.h ../../simos/elevator.h ../../lib/utility.h \
 ../../simos/callback.h ../../lib/list.h ../../lib/debug.h \
 ../../lib/sysdep.h /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../lib/list.cc \
 ../../threads/synch.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../simos/interrupt.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h
elevator.o: ../../simos/elevator.cc ../../lib/copyright.h \
 ../../simos/elevator.h ../../lib/utility.h ../../simos/callback.h \
 ../../lib/list.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../lib/list.cc \
 ../../threads/kernel.h ../../threads/thread.h ../../simos/machine.h \
 ../../simos/translate.h ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../simos/interrupt.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h ../../threads/main.h ../../userprog/userkernel.h
simos.o: ../../simos/simos.cc \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/malloc.h \
 /usr/class/cs240a/w97/mips-sgi/include/stddef.h ../../simos/machine.h \
 ../../lib/copyright.h ../../lib/utility.h ../../simos/translate.h \
 ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../threads/thread.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h \
 ../../filesys/openfile.h \
 /usr/class/cs240a/w97/lib/gcc-lib/mips-sgi/2.7.2/include/stdarg.h \
 /usr/class/cs240a/w97/lib/gcc-lib/mips-sgi/2.7.2/include/va-mips.h
addrspace.o: ../../userprog/addrspace.cc ../../lib/copyright.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/utility.h \
 ../../lib/sysdep.h /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h ../../bin/noff.h
exception.o: ../../userprog/exception.cc ../../lib/copyright.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/utility.h \
 ../../lib/sysdep.h /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h ../../userprog/syscall.h
synchconsole.o: ../../userprog/synchconsole.cc ../../lib/copyright.h \
 ../../userprog/synchconsole.h ../../lib/utility.h \
 ../../simos/callback.h ../../simos/console.h ../../threads/synch.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/stats.h ../../threads/alarm.h \
 ../../simos/timer.h ../../filesys/synchdisk.h ../../simos/disk.h
userkernel.o: ../../userprog/userkernel.cc ../../lib/copyright.h \
 ../../userprog/synchconsole.h ../../lib/utility.h \
 ../../simos/callback.h ../../simos/console.h ../../threads/synch.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/stats.h ../../threads/alarm.h \
 ../../simos/timer.h ../../filesys/synchdisk.h ../../simos/disk.h
console.o: ../../simos/console.cc ../../lib/copyright.h \
 ../../simos/console.h ../../lib/utility.h ../../simos/callback.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/stats.h ../../threads/alarm.h \
 ../../simos/timer.h ../../filesys/synchdisk.h ../../simos/disk.h
directory.o: ../../filesys/directory.cc ../../lib/copyright.h \
 ../../lib/utility.h ../../filesys/filehdr.h ../../filesys/synchdisk.h \
 ../../simos/disk.h ../../simos/callback.h ../../filesys/pbitmap.h \
 ../../lib/bitmap.h ../../filesys/openfile.h ../../filesys/directory.h
filehdr.o: ../../filesys/filehdr.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../filesys/filehdr.h ../../filesys/synchdisk.h ../../simos/disk.h \
 ../../simos/callback.h ../../filesys/pbitmap.h ../../lib/bitmap.h \
 ../../filesys/openfile.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../threads/scheduler.h ../../lib/list.h \
 ../../lib/list.cc ../../simos/interrupt.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h
filesys.o: ../../filesys/filesys.cc ../../lib/copyright.h \
 ../../simos/disk.h ../../lib/utility.h ../../simos/callback.h \
 ../../filesys/pbitmap.h ../../lib/bitmap.h ../../filesys/openfile.h \
 ../../filesys/directory.h ../../filesys/filehdr.h \
 ../../filesys/synchdisk.h ../../filesys/filesys.h ../../lib/debug.h \
 ../../lib/sysdep.h /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h
fstest.o: ../../filesys/fstest.cc ../../lib/copyright.h \
 ../../lib/utility.h ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/thread.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../simos/machine.h \
 ../../simos/translate.h ../../lib/debug.h ../../simos/registers.h \
 ../../simos/simos.h ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../simos/disk.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/main.h ../../userprog/userkernel.h \
 ../../threads/kernel.h ../../threads/scheduler.h ../../lib/list.h \
 ../../lib/list.cc ../../simos/interrupt.h ../../threads/alarm.h \
 ../../simos/timer.h ../../filesys/synchdisk.h
openfile.o: ../../filesys/openfile.cc ../../lib/copyright.h \
 ../../filesys/filehdr.h ../../filesys/synchdisk.h ../../simos/disk.h \
 ../../lib/utility.h ../../simos/callback.h ../../filesys/pbitmap.h \
 ../../lib/bitmap.h ../../filesys/openfile.h ../../threads/main.h \
 ../../lib/debug.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../threads/scheduler.h ../../lib/list.h \
 ../../lib/list.cc ../../simos/interrupt.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h
pbitmap.o: ../../filesys/pbitmap.cc ../../lib/copyright.h \
 ../../filesys/pbitmap.h ../../lib/bitmap.h ../../lib/utility.h \
 ../../filesys/openfile.h
synchdisk.o: ../../filesys/synchdisk.cc ../../lib/copyright.h \
 ../../threads/synch.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/callback.h ../../simos/stats.h \
 ../../threads/alarm.h ../../simos/timer.h ../../filesys/synchdisk.h \
 ../../simos/disk.h
disk.o: ../../simos/disk.cc ../../lib/copyright.h ../../simos/disk.h \
 ../../lib/utility.h ../../simos/callback.h ../../lib/debug.h \
 ../../lib/sysdep.h /usr/class/cs240a/w97/mips-sgi/include/stdlib.h \
 /usr/class/cs240a/w97/mips-sgi/include/sgidefs.h \
 /usr/class/cs240a/w97/mips-sgi/include/stdio.h \
 /usr/class/cs240a/w97/mips-sgi/include/string.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../simos/machine.h ../../simos/translate.h \
 ../../simos/registers.h ../../simos/simos.h \
 ../../simos/simmachine/simtypes.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/bsd_types.h \
 /usr/class/cs240a/w97/mips-sgi/include/sys/select.h \
 ../../simos/simmachine/mips_arch.h \
 ../../simos/simmachine/addr_layout.h \
 ../../simos/simmachine/machine_defs.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../filesys/openfile.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../simos/interrupt.h ../../simos/stats.h ../../threads/alarm.h \
 ../../simos/timer.h ../../filesys/synchdisk.h
# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# see make depend above
