# NOTE: this is a GNU Makefile.  You must use "gmake" rather than "make".

include ../Makefile.ALL

#-----------------------------------------------------------------
# DO NOT DELETE THIS LINE -- make depend uses it
#
bitmap.o: ../../lib/bitmap.cc ../../lib/copyright.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h ../../lib/bitmap.h
debug.o: ../../lib/debug.cc ../../lib/copyright.h ../../lib/utility.h \
 ../../lib/debug.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h
hash.o: ../../lib/hash.cc ../../lib/copyright.h
libtest.o: ../../lib/libtest.cc ../../lib/copyright.h \
 ../../lib/libtest.h ../../lib/bitmap.h ../../lib/utility.h \
 ../../lib/list.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../lib/list.cc ../../lib/hash.h ../../lib/hash.cc
list.o: ../../lib/list.cc ../../lib/copyright.h
sysdep.o: ../../lib/sysdep.cc ../../lib/copyright.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 /usr/include/unistd.h /usr/include/sys/types.h \
 /usr/include/sys/isa_defs.h /usr/include/sys/machtypes.h \
 /usr/include/sys/select.h /usr/include/sys/time.h /usr/include/time.h \
 /usr/include/sys/siginfo.h /usr/include/sys/machsig.h \
 /usr/include/sys/unistd.h /usr/include/sys/file.h \
 /usr/include/sys/t_lock.h /usr/include/sys/machlock.h \
 /usr/include/sys/dki_lkinfo.h /usr/include/sys/dl.h \
 /usr/include/sys/sleepq.h /usr/include/sys/turnstile.h \
 /usr/include/sys/param.h /usr/include/sys/pirec.h \
 /usr/include/sys/mutex.h /usr/include/sys/rwlock.h \
 /usr/include/sys/semaphore.h /usr/include/sys/condvar.h \
 /usr/include/sys/socket.h /usr/include/sys/netconfig.h \
 /usr/include/sys/un.h /usr/include/signal.h /usr/include/sys/signal.h \
 /usr/include/sys/procset.h /usr/include/sys/mman.h \
 /usr/include/fcntl.h /usr/include/sys/fcntl.h
interrupt.o: ../../machine/interrupt.cc ../../lib/copyright.h \
 ../../machine/interrupt.h ../../lib/list.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h ../../lib/list.cc \
 ../../machine/callback.h ../../threads/main.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/scheduler.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h
stats.o: ../../machine/stats.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../machine/stats.h
timer.o: ../../machine/timer.cc ../../lib/copyright.h \
 ../../machine/timer.h ../../lib/utility.h ../../machine/callback.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/kernel.h ../../threads/thread.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../machine/interrupt.h ../../machine/stats.h ../../threads/alarm.h
alarm.o: ../../threads/alarm.cc ../../lib/copyright.h \
 ../../threads/alarm.h ../../lib/utility.h ../../machine/callback.h \
 ../../machine/timer.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/kernel.h ../../threads/thread.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../machine/interrupt.h ../../machine/stats.h
kernel.o: ../../threads/kernel.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/main.h ../../threads/kernel.h ../../threads/thread.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../threads/synch.h ../../threads/synchlist.h \
 ../../threads/synchlist.cc ../../lib/libtest.h \
 ../../machine/elevatortest.h
main.o: ../../threads/main.cc ../../lib/copyright.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/utility.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/kernel.h ../../threads/thread.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h
scheduler.o: ../../threads/scheduler.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../threads/thread.h ../../threads/main.h ../../threads/kernel.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h
synch.o: ../../threads/synch.cc ../../lib/copyright.h \
 ../../threads/synch.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/kernel.h ../../threads/thread.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h
synchlist.o: ../../threads/synchlist.cc ../../lib/copyright.h \
 ../../threads/synchlist.h ../../lib/list.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h ../../lib/list.cc \
 ../../threads/synch.h ../../threads/main.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../threads/synchlist.cc
thread.o: ../../threads/thread.cc ../../lib/copyright.h \
 ../../threads/thread.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/switch.h ../../threads/synch.h ../../threads/main.h \
 ../../lib/debug.h ../../threads/kernel.h ../../threads/scheduler.h \
 ../../lib/list.h ../../lib/list.cc ../../machine/interrupt.h \
 ../../machine/callback.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h
elevatortest.o: ../../machine/elevatortest.cc ../../lib/copyright.h \
 ../../machine/elevatortest.h ../../machine/elevator.h \
 ../../lib/utility.h ../../machine/callback.h ../../lib/list.h \
 ../../lib/debug.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h ../../lib/list.cc \
 ../../threads/synch.h ../../threads/main.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h
elevator.o: ../../machine/elevator.cc ../../lib/copyright.h \
 ../../machine/elevator.h ../../lib/utility.h ../../machine/callback.h \
 ../../lib/list.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../lib/list.cc ../../threads/main.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h
# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# see make depend above
