# NOTE: this is a GNU Makefile.  You must use "gmake" rather than "make".

include ../Makefile.ALL

#-----------------------------------------------------------------
# DO NOT DELETE THIS LINE -- make depend uses it
# DEPENDENCIES MUST END AT END OF FILE
bitmap.o: ../../lib/bitmap.cc ../../lib/copyright.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h ../../lib/bitmap.h
debug.o: ../../lib/debug.cc ../../lib/copyright.h ../../lib/utility.h \
 ../../lib/debug.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h
hash.o: ../../lib/hash.cc ../../lib/copyright.h
libtest.o: ../../lib/libtest.cc ../../lib/copyright.h \
 ../../lib/libtest.h ../../lib/bitmap.h ../../lib/utility.h \
 ../../lib/list.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../lib/list.cc ../../lib/hash.h ../../lib/hash.cc
list.o: ../../lib/list.cc ../../lib/copyright.h
sysdep.o: ../../lib/sysdep.cc ../../lib/copyright.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 /usr/include/unistd.h /usr/include/sys/types.h \
 /usr/include/sys/isa_defs.h /usr/include/sys/machtypes.h \
 /usr/include/sys/int_types.h /usr/include/sys/select.h \
 /usr/include/sys/time.h /usr/include/time.h \
 /usr/include/sys/siginfo.h /usr/include/sys/machsig.h \
 /usr/include/sys/unistd.h /usr/include/sys/file.h \
 /usr/include/sys/t_lock.h /usr/include/sys/machlock.h \
 /usr/include/sys/sleepq.h /usr/include/sys/turnstile.h \
 /usr/include/sys/param.h /usr/include/sys/pirec.h \
 /usr/include/sys/mutex.h /usr/include/sys/rwlock.h \
 /usr/include/sys/semaphore.h /usr/include/sys/condvar.h \
 /usr/include/sys/socket.h /usr/include/sys/uio.h \
 /usr/include/sys/netconfig.h /usr/include/sys/un.h \
 /usr/include/signal.h /usr/include/sys/signal.h \
 /usr/include/sys/procset.h /usr/include/sys/mman.h \
 /usr/include/fcntl.h /usr/include/sys/fcntl.h
interrupt.o: ../../machine/interrupt.cc ../../lib/copyright.h \
 ../../machine/interrupt.h ../../lib/list.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h ../../lib/list.cc \
 ../../machine/callback.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h \
 ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
stats.o: ../../machine/stats.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../machine/stats.h
timer.o: ../../machine/timer.cc ../../lib/copyright.h \
 ../../machine/timer.h ../../lib/utility.h ../../machine/callback.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/stats.h ../../threads/alarm.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
alarm.o: ../../threads/alarm.cc ../../lib/copyright.h \
 ../../threads/alarm.h ../../lib/utility.h ../../machine/callback.h \
 ../../machine/timer.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/stats.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
kernel.o: ../../threads/kernel.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/main.h ../../userprog/userkernel.h \
 ../../threads/kernel.h ../../threads/thread.h \
 ../../threads/constants.h ../../lib/list.h ../../lib/list.cc \
 ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h ../../threads/synchlist.h \
 ../../threads/synchlist.cc ../../lib/libtest.h \
 ../../machine/elevatortest.h
main.o: ../../threads/main.cc ../../lib/copyright.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/utility.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
scheduler.o: ../../threads/scheduler.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/scheduler.h ../../lib/list.h ../../lib/list.cc \
 ../../threads/thread.h ../../threads/constants.h \
 ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
synch.o: ../../threads/synch.cc ../../lib/copyright.h \
 ../../threads/synch.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../userprog/memman.h ../../lib/bitmap.h ../../userprog/swapman.h
synchlist.o: ../../threads/synchlist.cc ../../lib/copyright.h \
 ../../threads/synchlist.h ../../lib/list.h ../../lib/debug.h \
 ../../lib/utility.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h ../../lib/list.cc \
 ../../threads/synch.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h \
 ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../userprog/memman.h ../../lib/bitmap.h ../../userprog/swapman.h \
 ../../threads/synchlist.cc
thread.o: ../../threads/thread.cc ../../lib/copyright.h \
 ../../threads/thread.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../threads/constants.h ../../lib/list.h ../../lib/debug.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/switch.h \
 ../../threads/synch.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/scheduler.h ../../machine/interrupt.h \
 ../../machine/callback.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h ../../userprog/synchconsole.h \
 ../../machine/console.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
elevatortest.o: ../../machine/elevatortest.cc ../../lib/copyright.h \
 ../../machine/elevatortest.h ../../machine/elevator.h \
 ../../lib/utility.h ../../machine/callback.h ../../lib/list.h \
 ../../lib/debug.h ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h ../../lib/list.cc \
 ../../threads/synch.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h \
 ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h ../../userprog/synchconsole.h \
 ../../machine/console.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
elevator.o: ../../machine/elevator.cc ../../lib/copyright.h \
 ../../machine/elevator.h ../../lib/utility.h ../../machine/callback.h \
 ../../lib/list.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../lib/list.cc ../../threads/main.h ../../userprog/userkernel.h \
 ../../threads/kernel.h ../../threads/thread.h \
 ../../threads/constants.h ../../filesys/openfile.h \
 ../../machine/machine.h ../../machine/translate.h \
 ../../machine/registers.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../lib/hash.h ../../lib/hash.cc \
 ../../bin/noff.h ../../threads/scheduler.h ../../machine/interrupt.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
addrspace.o: ../../userprog/addrspace.cc ../../lib/copyright.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/utility.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
exception.o: ../../userprog/exception.cc ../../lib/copyright.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/utility.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h ../../userprog/syscall.h
synchconsole.o: ../../userprog/synchconsole.cc ../../lib/copyright.h \
 ../../userprog/synchconsole.h ../../lib/utility.h \
 ../../machine/callback.h ../../machine/console.h \
 ../../threads/synch.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
userkernel.o: ../../userprog/userkernel.cc ../../lib/copyright.h \
 ../../userprog/synchconsole.h ../../lib/utility.h \
 ../../machine/callback.h ../../machine/console.h \
 ../../threads/synch.h ../../threads/main.h ../../lib/debug.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
memman.o: ../../userprog/memman.cc ../../threads/constants.h \
 ../../userprog/memman.h ../../lib/list.h ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../lib/list.cc ../../lib/hash.h ../../lib/hash.cc \
 ../../lib/bitmap.h ../../threads/synch.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../filesys/openfile.h \
 ../../machine/machine.h ../../machine/translate.h \
 ../../machine/registers.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../userprog/swapman.h
swapman.o: ../../userprog/swapman.cc ../../threads/constants.h \
 ../../userprog/swapman.h ../../lib/list.h ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../lib/list.cc ../../lib/hash.h ../../lib/hash.cc \
 ../../lib/bitmap.h ../../threads/synch.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../filesys/openfile.h \
 ../../machine/machine.h ../../machine/translate.h \
 ../../machine/registers.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../userprog/memman.h
console.o: ../../machine/console.cc ../../lib/copyright.h \
 ../../machine/console.h ../../lib/utility.h ../../machine/callback.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h ../../userprog/synchconsole.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
mipssim.o: ../../machine/mipssim.cc ../../lib/copyright.h \
 ../../lib/debug.h ../../lib/utility.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../machine/machine.h ../../threads/constants.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../machine/mipssim.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../lib/list.h ../../lib/list.cc \
 ../../filesys/openfile.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../lib/hash.h ../../lib/hash.cc \
 ../../bin/noff.h ../../threads/scheduler.h ../../machine/interrupt.h \
 ../../machine/callback.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h ../../userprog/synchconsole.h \
 ../../machine/console.h ../../threads/synch.h ../../userprog/memman.h \
 ../../lib/bitmap.h ../../userprog/swapman.h
translate.o: ../../machine/translate.cc ../../lib/copyright.h \
 ../../threads/main.h ../../lib/debug.h ../../lib/utility.h \
 ../../lib/sysdep.h /usr/include/stdlib.h \
 /usr/include/sys/feature_tests.h /usr/include/stdio.h \
 /usr/include/sys/va_list.h /usr/include/string.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../threads/constants.h ../../lib/list.h \
 ../../lib/list.cc ../../filesys/openfile.h ../../machine/machine.h \
 ../../machine/translate.h ../../machine/registers.h \
 ../../userprog/addrspace.h ../../filesys/filesys.h ../../lib/hash.h \
 ../../lib/hash.cc ../../bin/noff.h ../../threads/scheduler.h \
 ../../machine/interrupt.h ../../machine/callback.h \
 ../../machine/stats.h ../../threads/alarm.h ../../machine/timer.h \
 ../../userprog/synchconsole.h ../../machine/console.h \
 ../../threads/synch.h ../../userprog/memman.h ../../lib/bitmap.h \
 ../../userprog/swapman.h
machine.o: ../../machine/machine.cc ../../lib/copyright.h \
 ../../machine/machine.h ../../threads/constants.h ../../lib/utility.h \
 ../../machine/translate.h ../../lib/debug.h ../../lib/sysdep.h \
 /usr/include/stdlib.h /usr/include/sys/feature_tests.h \
 /usr/include/stdio.h /usr/include/sys/va_list.h /usr/include/string.h \
 ../../machine/registers.h ../../threads/main.h \
 ../../userprog/userkernel.h ../../threads/kernel.h \
 ../../threads/thread.h ../../lib/list.h ../../lib/list.cc \
 ../../filesys/openfile.h ../../userprog/addrspace.h \
 ../../filesys/filesys.h ../../lib/hash.h ../../lib/hash.cc \
 ../../bin/noff.h ../../threads/scheduler.h ../../machine/interrupt.h \
 ../../machine/callback.h ../../machine/stats.h ../../threads/alarm.h \
 ../../machine/timer.h ../../userprog/synchconsole.h \
 ../../machine/console.h ../../threads/synch.h ../../userprog/memman.h \
 ../../lib/bitmap.h ../../userprog/swapman.h
# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# see make depend above
